# Generated by Django 4.2.17 on 2026-05-06 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sku_mgt', '0003_sku_code_not_blank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sku',
            name='sku_code',
            field=models.CharField(db_index=True, max_length=64, unique=True),
        ),
    ]
