<template><div class="page-container"><el-card><template #header><span>采购单</span><el-button type="primary" size="small" style="float:right">新建采购单</el-button></template><el-form :inline="true"><el-form-item label="状态"><el-select v-model="f.status" clearable><el-option v-for="s in ['PENDING','AUDITED','SHIPPED','ARRIVED','COMPLETED','CANCELLED']" :key="s" :label="s" :value="s"/></el-select></el-form-item><el-form-item label="采购类型"><el-select v-model="f.order_type" clearable><el-option label="普通" value="NORMAL"/><el-option label="1688" value="1688"/></el-select></el-form-item><el-form-item label="搜索"><el-input v-model="f.search" placeholder="订单号/创建人" clearable style="width:200px"/></el-form-item><el-form-item><el-button type="primary" @click="search">查询</el-button></el-form-item></el-form><el-table :data="list" border stripe v-loading="loading"><el-table-column prop="order_no" label="订单号" width="150"/><el-table-column prop="order_type" label="类型" width="80"/><el-table-column label="供应商" width="120"><template #default="{ row }"><span>{{ row.supplier_name || r.supplier }}</span></template></el-table-column><el-table-column prop="total_amount" label="总金额" width="120"/><el-table-column prop="tax_amount" label="税额" width="100"/><el-table-column prop="status" label="状态" width="100"/><el-table-column prop="order_date" label="订单日期" width="120"/><el-table-column prop="creator" label="创建人" width="100"/><el-table-column label="操作" width="150" fixed="right"><template #default="{ row }"><el-button size="small" @click="handleDetail(r)">详情</el-button><el-button size="small" type="warning" @click="handleAudit(r)">审核</el-button></template></el-table-column></el-table><el-pagination v-model:current-page="p.page" layout="total,prev,pager,next" :total="p.total" @current-change="load"/></el-card></div></template>
<script setup>import { ref, reactive, onMounted } from 'vue'; import { purchaseOrderApi } from '@/api/purchase'; import { ElMessage } from 'element-plus'
const f = reactive({ status: '', order_type: '', search: '' }); const list = ref([]); const loading = ref(false); const p = reactive({ page: 1, total: 0 })
async function load() { loading.value = true; try { const data = await purchaseOrderApi.list({ ...f, page: p.page }); list.value = data?.results || data || []; p.total = data?.count || 0 } catch { } finally { loading.value = false } }
function search() { p.page = 1; load() }
function handleDetail(r) { ElMessage.info(`详情: ${r.order_no}`) }
function handleAudit(r) { ElMessage.info(`审核: ${r.order_no}`) }
onMounted(load)
</script>
