<template><div class="page-container"><el-card><template #header><span>供应商管理</span><el-button type="primary" size="small" style="float:right">新增供应商</el-button></template><el-form :inline="true"><el-form-item label="状态"><el-select v-model="f.status" clearable><el-option label="启用" :value="true"/><el-option label="停用" :value="false"/></el-select></el-form-item><el-form-item label="搜索"><el-input v-model="f.search" placeholder="名称/编码/联系人" clearable style="width:200px"/></el-form-item><el-form-item><el-button type="primary" @click="search">查询</el-button></el-form-item></el-form><el-table :data="list" border stripe v-loading="loading"><el-table-column prop="code" label="编码" width="100"/><el-table-column prop="name" label="名称" width="150"/><el-table-column prop="contact_name" label="联系人" width="100"/><el-table-column prop="phone" label="电话" width="120"/><el-table-column prop="settlement_method" label="结算方式" width="100"/><el-table-column prop="status" label="状态" width="80"><template #default="{ row }"><el-tag :type="row.status?'success':'info'">{{row.status?'启用':'停用'}}</el-tag></template></el-table-column><el-table-column prop="created_at" label="创建时间" width="160"/><el-table-column label="操作" width="150" fixed="right"><template #default="{ row }"><el-button size="small" @click="handleEdit(r)">编辑</el-button><el-button size="small" type="danger" @click="handleDelete(r)">删除</el-button></template></el-table-column></el-table><el-pagination v-model:current-page="p.page" layout="total,prev,pager,next" :total="p.total" @current-change="load"/></el-card></div></template>
<script setup>import { ref, reactive, onMounted } from 'vue'; import { supplierApi } from '@/api/purchase'; import { ElMessage } from 'element-plus'
const f = reactive({ status: '', search: '' }); const list = ref([]); const loading = ref(false); const p = reactive({ page: 1, total: 0 })
async function load() { loading.value = true; try { const data = await supplierApi.list({ ...f, page: p.page }); list.value = data?.results || data || []; p.total = data?.count || 0 } catch { } finally { loading.value = false } }
function search() { p.page = 1; load() }
function handleEdit(r) { ElMessage.info(`编辑: ${r.name}`) }
function handleDelete(r) { ElMessage.info(`删除: ${r.name}`) }
onMounted(load)
</script>
