# Generated by Django 4.2.17 on 2026-05-07 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_core_logist_carrier_4b834f_idx_core_logist_carrier_a3ffd5_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('code', models.CharField(db_index=True, max_length=64, unique=True)),
                ('address', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(db_index=True, default='active', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['code', 'status'], name='core_wareho_code_5dbf9a_idx')],
            },
        ),
        migrations.CreateModel(
            name='InventoryAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(db_index=True, max_length=128)),
                ('adjustment_type', models.CharField(choices=[('increase', 'Increase'), ('decrease', 'Decrease'), ('set', 'Set')], max_length=32)),
                ('quantity', models.IntegerField()),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('operator', models.CharField(default='system', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='OrderRemark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('operator', models.CharField(default='system', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remarks', to='core.order')),
            ],
            options={
                'indexes': [models.Index(fields=['order', 'created_at'], name='core_orderr_order_i_d141bd_idx')],
            },
        ),
    ]
