# Generated by Django 4.2.17 on 2026-05-12 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_warehouse_inventoryadjustment_orderremark'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='abnormality_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='inventoryadjustment',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.product'),
        ),
        migrations.AlterField(
            model_name='inventoryadjustment',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.warehouse'),
        ),
        migrations.AlterField(
            model_name='logisticsshipment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='core.order'),
        ),
        migrations.AlterField(
            model_name='logisticstrackingevent',
            name='shipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tracking_events', to='core.logisticsshipment'),
        ),
        migrations.AlterField(
            model_name='orderremark',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='remarks', to='core.order'),
        ),
        migrations.AlterField(
            model_name='platformorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='platform_payloads', to='core.order'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variants', to='core.product'),
        ),
        migrations.AlterField(
            model_name='replayauditlog',
            name='dead_letter_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='replay_logs', to='core.deadlettertask'),
        ),
    ]
