# Generated by Django 4.2.17 on 2026-05-12 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_order_abnormality_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logisticsshipment',
            name='abnormal_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
