# Generated by Django 6.0.4 on 2026-05-18 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=50, unique=True, verbose_name='单据编号')),
                ('source_type', models.CharField(blank=True, default='', max_length=50, verbose_name='来源类型')),
                ('source_id', models.BigIntegerField(blank=True, null=True, verbose_name='来源单据ID')),
                ('wave_no', models.CharField(blank=True, default='', max_length=50, verbose_name='波次号')),
                ('status', models.IntegerField(db_index=True, default=0, verbose_name='状态(0待审核1已审核2拣货中3已发货)')),
                ('creator', models.CharField(blank=True, default='', max_length=50, verbose_name='创建人')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '出库单',
                'verbose_name_plural': '出库单',
                'db_table': 'wms_delivery_order',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100, verbose_name='商品SKU')),
                ('sku_name', models.CharField(blank=True, default='', max_length=200, verbose_name='商品名称')),
                ('quantity', models.DecimalField(decimal_places=4, default=0, max_digits=18, verbose_name='可用库存')),
                ('locked_qty', models.DecimalField(decimal_places=4, default=0, max_digits=18, verbose_name='锁定库存')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '库存',
                'verbose_name_plural': '库存',
                'db_table': 'wms_inventory',
            },
        ),
        migrations.CreateModel(
            name='InventoryCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=50, unique=True, verbose_name='单据编号')),
                ('status', models.IntegerField(db_index=True, default=0, verbose_name='状态(0待盘点1盘点中2已完成)')),
                ('creator', models.CharField(blank=True, default='', max_length=50, verbose_name='创建人')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '盘点单',
                'verbose_name_plural': '盘点单',
                'db_table': 'wms_inventory_check',
            },
        ),
        migrations.CreateModel(
            name='PackingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_no', models.CharField(max_length=50, unique=True, verbose_name='任务编号')),
                ('status', models.IntegerField(db_index=True, default=0, verbose_name='状态(0待执行1装箱中2已完成)')),
                ('box_count', models.IntegerField(default=0, verbose_name='箱子数量')),
                ('creator', models.CharField(blank=True, default='', max_length=50, verbose_name='创建人')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '装箱任务',
                'verbose_name_plural': '装箱任务',
                'db_table': 'wms_packing_task',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100, unique=True, verbose_name='商品SKU')),
                ('sku_name', models.CharField(max_length=200, verbose_name='商品名称')),
                ('fnsku', models.CharField(blank=True, default='', max_length=100, verbose_name='FNSKU')),
                ('msku', models.CharField(blank=True, default='', max_length=100, verbose_name='MSKU')),
                ('asin', models.CharField(blank=True, default='', max_length=50, verbose_name='ASIN')),
                ('upc', models.CharField(blank=True, default='', max_length=50, verbose_name='UPC')),
                ('category', models.CharField(blank=True, default='', max_length=100, verbose_name='商品分类')),
                ('brand', models.CharField(blank=True, default='', max_length=100, verbose_name='品牌')),
                ('weight', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='重量(kg)')),
                ('length', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='长度(cm)')),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='宽度(cm)')),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='高度(cm)')),
                ('image_url', models.CharField(blank=True, default='', max_length=500, verbose_name='商品图片URL')),
                ('product_status', models.CharField(default='ACTIVE', max_length=20, verbose_name='商品状态')),
                ('listing_owner', models.CharField(blank=True, default='', max_length=50, verbose_name='Listing负责人')),
                ('product_owner', models.CharField(blank=True, default='', max_length=50, verbose_name='产品负责人')),
                ('tags', models.CharField(blank=True, default='', max_length=500, verbose_name='商品标签')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
                'db_table': 'wms_product',
            },
        ),
        migrations.CreateModel(
            name='ReceiptOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=50, unique=True, verbose_name='单据编号')),
                ('source_type', models.CharField(blank=True, default='', max_length=50, verbose_name='来源类型')),
                ('source_id', models.BigIntegerField(blank=True, null=True, verbose_name='来源单据ID')),
                ('status', models.IntegerField(db_index=True, default=0, verbose_name='状态(0待审核1已审核2已完成3已驳回)')),
                ('creator', models.CharField(blank=True, default='', max_length=50, verbose_name='创建人')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '收货单',
                'verbose_name_plural': '收货单',
                'db_table': 'wms_receipt_order',
            },
        ),
        migrations.CreateModel(
            name='TransferOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=50, unique=True, verbose_name='单据编号')),
                ('status', models.IntegerField(db_index=True, default=0, verbose_name='状态(0待审核1已审核2已出库3已入库)')),
                ('creator', models.CharField(blank=True, default='', max_length=50, verbose_name='创建人')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '调拨单',
                'verbose_name_plural': '调拨单',
                'db_table': 'wms_transfer_order',
            },
        ),
        migrations.CreateModel(
            name='WarehouseWms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='仓库名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='仓库编码')),
                ('address', models.CharField(blank=True, default='', max_length=500, verbose_name='仓库地址')),
                ('status', models.BooleanField(default=True, verbose_name='启用状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '仓库',
                'verbose_name_plural': '仓库',
                'db_table': 'wms_warehouse',
            },
        ),
        migrations.CreateModel(
            name='DeliveryOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100, verbose_name='商品SKU')),
                ('sku_name', models.CharField(blank=True, default='', max_length=200, verbose_name='商品名称')),
                ('fnsku', models.CharField(blank=True, default='', max_length=100, verbose_name='FNSKU')),
                ('order_qty', models.DecimalField(decimal_places=4, max_digits=18, verbose_name='出库数量')),
                ('picked_qty', models.DecimalField(decimal_places=4, default=0, max_digits=18, verbose_name='已拣货数量')),
                ('shipped_qty', models.DecimalField(decimal_places=4, default=0, max_digits=18, verbose_name='已发货数量')),
                ('batch_no', models.CharField(blank=True, default='', max_length=100, verbose_name='批次号')),
                ('remark', models.CharField(blank=True, default='', max_length=500, verbose_name='备注')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='wms.deliveryorder', verbose_name='出库单')),
            ],
            options={
                'verbose_name': '出库单明细',
                'verbose_name_plural': '出库单明细',
                'db_table': 'wms_delivery_order_item',
            },
        ),
        migrations.CreateModel(
            name='InventoryBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_no', models.CharField(max_length=100, verbose_name='批次号')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='有效期')),
                ('quantity', models.DecimalField(decimal_places=4, default=0, max_digits=18, verbose_name='批次数量')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='wms.inventory', verbose_name='库存')),
            ],
            options={
                'verbose_name': '库存批次',
                'verbose_name_plural': '库存批次',
                'db_table': 'wms_inventory_batch',
            },
        ),
        migrations.CreateModel(
            name='InventoryCheckItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100, verbose_name='商品SKU')),
                ('sku_name', models.CharField(blank=True, default='', max_length=200, verbose_name='商品名称')),
                ('system_qty', models.DecimalField(decimal_places=4, max_digits=18, verbose_name='系统库存')),
                ('actual_qty', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='实际盘点数量')),
                ('diff_qty', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='差异数量')),
                ('batch_no', models.CharField(blank=True, default='', max_length=100, verbose_name='批次号')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='wms.inventorycheck', verbose_name='盘点单')),
            ],
            options={
                'verbose_name': '盘点单明细',
                'verbose_name_plural': '盘点单明细',
                'db_table': 'wms_inventory_check_item',
            },
        ),
        migrations.CreateModel(
            name='PackingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_no', models.CharField(max_length=50, verbose_name='箱号')),
                ('sku', models.CharField(max_length=100, verbose_name='商品SKU')),
                ('qty', models.DecimalField(decimal_places=4, max_digits=18, verbose_name='装箱数量')),
                ('barcode', models.CharField(blank=True, default='', max_length=100, verbose_name='条码')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='wms.packingtask', verbose_name='装箱任务')),
            ],
            options={
                'verbose_name': '装箱明细',
                'verbose_name_plural': '装箱明细',
                'db_table': 'wms_packing_item',
            },
        ),
        migrations.CreateModel(
            name='ReceiptOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100, verbose_name='商品SKU')),
                ('sku_name', models.CharField(blank=True, default='', max_length=200, verbose_name='商品名称')),
                ('fnsku', models.CharField(blank=True, default='', max_length=100, verbose_name='FNSKU')),
                ('expected_qty', models.DecimalField(decimal_places=4, max_digits=18, verbose_name='预期收货数量')),
                ('actual_qty', models.DecimalField(decimal_places=4, default=0, max_digits=18, verbose_name='实际收货数量')),
                ('qualified_qty', models.DecimalField(decimal_places=4, default=0, max_digits=18, verbose_name='合格品数量')),
                ('defective_qty', models.DecimalField(decimal_places=4, default=0, max_digits=18, verbose_name='不合格品数量')),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='单位成本')),
                ('batch_no', models.CharField(blank=True, default='', max_length=100, verbose_name='批次号')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='有效期')),
                ('remark', models.CharField(blank=True, default='', max_length=500, verbose_name='备注')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='wms.receiptorder', verbose_name='收货单')),
            ],
            options={
                'verbose_name': '收货单明细',
                'verbose_name_plural': '收货单明细',
                'db_table': 'wms_receipt_order_item',
            },
        ),
        migrations.CreateModel(
            name='TransferOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100, verbose_name='商品SKU')),
                ('sku_name', models.CharField(blank=True, default='', max_length=200, verbose_name='商品名称')),
                ('qty', models.DecimalField(decimal_places=4, max_digits=18, verbose_name='调拨数量')),
                ('batch_no', models.CharField(blank=True, default='', max_length=100, verbose_name='批次号')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='wms.transferorder', verbose_name='调拨单')),
            ],
            options={
                'verbose_name': '调拨单明细',
                'verbose_name_plural': '调拨单明细',
                'db_table': 'wms_transfer_order_item',
            },
        ),
        migrations.AddField(
            model_name='transferorder',
            name='from_warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='wms.warehousewms', verbose_name='调出仓库'),
        ),
        migrations.AddField(
            model_name='transferorder',
            name='to_warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='wms.warehousewms', verbose_name='调入仓库'),
        ),
        migrations.AddField(
            model_name='receiptorder',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wms.warehousewms', verbose_name='收货仓库'),
        ),
        migrations.AddField(
            model_name='packingtask',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wms.warehousewms', verbose_name='仓库'),
        ),
        migrations.CreateModel(
            name='OverseasStocking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=50, unique=True, verbose_name='单据编号')),
                ('status', models.IntegerField(db_index=True, default=0, verbose_name='状态(0待审核1已审核2已发货3已入库)')),
                ('creator', models.CharField(blank=True, default='', max_length=50, verbose_name='创建人')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wms.warehousewms', verbose_name='海外仓')),
            ],
            options={
                'verbose_name': '海外仓备货单',
                'verbose_name_plural': '海外仓备货单',
                'db_table': 'wms_overseas_stocking',
            },
        ),
        migrations.AddField(
            model_name='inventorycheck',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wms.warehousewms', verbose_name='盘点仓库'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventories', to='wms.warehousewms', verbose_name='仓库'),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wms.warehousewms', verbose_name='出库仓库'),
        ),
        migrations.CreateModel(
            name='Wave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wave_no', models.CharField(max_length=50, unique=True, verbose_name='波次编号')),
                ('status', models.IntegerField(db_index=True, default=0, verbose_name='状态(0待分配1拣货中2已完成)')),
                ('order_count', models.IntegerField(default=0, verbose_name='包含订单数')),
                ('item_count', models.IntegerField(default=0, verbose_name='包含商品项数')),
                ('creator', models.CharField(blank=True, default='', max_length=50, verbose_name='创建人')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wms.warehousewms', verbose_name='仓库')),
            ],
            options={
                'verbose_name': '波次',
                'verbose_name_plural': '波次',
                'db_table': 'wms_wave',
            },
        ),
        migrations.CreateModel(
            name='WaveOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.BigIntegerField(verbose_name='出库单ID')),
                ('order_no', models.CharField(max_length=50, verbose_name='订单编号')),
                ('wave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wms.wave', verbose_name='波次')),
            ],
            options={
                'verbose_name': '波次订单关联',
                'verbose_name_plural': '波次订单关联',
                'db_table': 'wms_wave_order',
            },
        ),
        migrations.CreateModel(
            name='StockFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow_type', models.CharField(max_length=50, verbose_name='流水类型(IN/OUT/ADJUST)')),
                ('change_qty', models.DecimalField(decimal_places=4, max_digits=18, verbose_name='变动数量')),
                ('before_qty', models.DecimalField(decimal_places=4, max_digits=18, verbose_name='变动前数量')),
                ('after_qty', models.DecimalField(decimal_places=4, max_digits=18, verbose_name='变动后数量')),
                ('order_no', models.CharField(blank=True, default='', max_length=50, verbose_name='关联单据号')),
                ('remark', models.CharField(blank=True, default='', max_length=500, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wms.inventory', verbose_name='库存')),
            ],
            options={
                'verbose_name': '库存流水',
                'verbose_name_plural': '库存流水',
                'db_table': 'wms_stock_flow',
                'indexes': [models.Index(fields=['inventory'], name='idx_wms_sf_inventory'), models.Index(fields=['created_at'], name='idx_wms_sf_created')],
            },
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['warehouse', 'sku'], name='idx_wms_ivt_wh_sku'),
        ),
    ]
