from rest_framework import serializers
from apps.finance.models import *

def _m(cls): return type(f'{cls.__name__}Serializer', (serializers.ModelSerializer,), {
    'Meta': type('Meta', (), {'model': cls, 'fields': '__all__', 'read_only_fields': ['id', 'created_at', 'updated_at']})
})

PaymentRequestPoolSerializer = _m(PaymentRequestPool)
PaymentRequestSerializer = _m(PaymentRequest)
PaymentRequestItemSerializer = _m(PaymentRequestItem)
PaymentRecordSerializer = _m(PaymentRecord)
ReceiptOrderSerializer = _m(ReceiptOrder)
ReceiptOrderItemSerializer = _m(ReceiptOrderItem)
TransactionFlowSerializer = _m(TransactionFlow)
OrderProfitSerializer = _m(OrderProfit)
SettlementProfitSerializer = _m(SettlementProfit)
BillDetailSerializer = _m(BillDetail)
CollectionDetailSerializer = _m(CollectionDetail)
ExpenseRecordSerializer = _m(ExpenseRecord)
CostDiagnosisSerializer = _m(CostDiagnosis)
CostResetRecordSerializer = _m(CostResetRecord)
CostValuationSerializer = _m(CostValuation)
WfsCostSerializer = _m(WfsCost)
ApprovalFlowSerializer = _m(ApprovalFlow)
AmazonSummaryReportSerializer = _m(AmazonSummaryReport)
ClosingPeriodSerializer = _m(ClosingPeriod)
ClosingLogSerializer = _m(ClosingLog)
ClosingSettingSerializer = _m(ClosingSetting)
AdInvoiceHeaderSerializer = _m(AdInvoiceHeader)
AdInvoiceDetailSerializer = _m(AdInvoiceDetail)
AdInvoiceAllocationSerializer = _m(AdInvoiceAllocation)
DelayedSettlementSerializer = _m(DelayedSettlement)
DelayedSettlementSettingSerializer = _m(DelayedSettlementSetting)
DelayedSettlementAdjustmentSerializer = _m(DelayedSettlementAdjustment)
ProfitReportConfigSerializer = _m(ProfitReportConfig)
ExpenseAllocationRuleSerializer = _m(ExpenseAllocationRule)
ProfitReportVersionSerializer = _m(ProfitReportVersion)
PerformanceReportSerializer = _m(PerformanceReport)
EmployeeDepartmentRelSerializer = _m(EmployeeDepartmentRel)
TurnoverHandoverSerializer = _m(TurnoverHandover)
ExpenseTypeSerializer = _m(ExpenseType)
ExpenseOrderSerializer = _m(ExpenseOrder)
ExpenseTemplateSerializer = _m(ExpenseTemplate)
ProfitCheckRuleSerializer = _m(ProfitCheckRule)

__all__ = [k for k in dir() if k.endswith('Serializer')]
