from rest_framework.routers import DefaultRouter
from apps.finance.views import *

router = DefaultRouter()
router.register(r'payment-pool', PaymentRequestPoolViewSet, basename='payment-pool')
router.register(r'payment-request', PaymentRequestViewSet, basename='payment-request')
router.register(r'payment-request-item', PaymentRequestItemViewSet, basename='payment-request-item')
router.register(r'payment-record', PaymentRecordViewSet, basename='payment-record')
router.register(r'receipt-order', ReceiptOrderViewSet, basename='receipt-order')
router.register(r'receipt-order-item', ReceiptOrderItemViewSet, basename='receipt-order-item')
router.register(r'transaction-flow', TransactionFlowViewSet, basename='transaction-flow')
router.register(r'order-profit', OrderProfitViewSet, basename='order-profit')
router.register(r'settlement-profit', SettlementProfitViewSet, basename='settlement-profit')
router.register(r'bill-detail', BillDetailViewSet, basename='bill-detail')
router.register(r'collection-detail', CollectionDetailViewSet, basename='collection-detail')
router.register(r'expense-record', ExpenseRecordViewSet, basename='expense-record')
router.register(r'cost-diagnosis', CostDiagnosisViewSet, basename='cost-diagnosis')
router.register(r'cost-reset-record', CostResetRecordViewSet, basename='cost-reset-record')
router.register(r'cost-valuation', CostValuationViewSet, basename='cost-valuation')
router.register(r'wfs-cost', WfsCostViewSet, basename='wfs-cost')
router.register(r'approval-flow', ApprovalFlowViewSet, basename='approval-flow')
router.register(r'amazon-summary-report', AmazonSummaryReportViewSet, basename='amazon-summary-report')
router.register(r'closing-period', ClosingPeriodViewSet, basename='closing-period')
router.register(r'closing-log', ClosingLogViewSet, basename='closing-log')
router.register(r'closing-setting', ClosingSettingViewSet, basename='closing-setting')
router.register(r'ad-invoice-header', AdInvoiceHeaderViewSet, basename='ad-invoice-header')
router.register(r'ad-invoice-detail', AdInvoiceDetailViewSet, basename='ad-invoice-detail')
router.register(r'ad-invoice-allocation', AdInvoiceAllocationViewSet, basename='ad-invoice-allocation')
router.register(r'delayed-settlement', DelayedSettlementViewSet, basename='delayed-settlement')
router.register(r'delayed-settlement-setting', DelayedSettlementSettingViewSet, basename='delayed-settlement-setting')
router.register(r'delayed-settlement-adjustment', DelayedSettlementAdjustmentViewSet, basename='delayed-settlement-adjustment')
router.register(r'profit-report-config', ProfitReportConfigViewSet, basename='profit-report-config')
router.register(r'expense-allocation-rule', ExpenseAllocationRuleViewSet, basename='expense-allocation-rule')
router.register(r'profit-report-version', ProfitReportVersionViewSet, basename='profit-report-version')
router.register(r'performance-report', PerformanceReportViewSet, basename='performance-report')
router.register(r'employee-department-rel', EmployeeDepartmentRelViewSet, basename='employee-department-rel')
router.register(r'turnover-handover', TurnoverHandoverViewSet, basename='turnover-handover')
router.register(r'expense-type', ExpenseTypeViewSet, basename='expense-type')
router.register(r'expense-order', ExpenseOrderViewSet, basename='expense-order')
router.register(r'expense-template', ExpenseTemplateViewSet, basename='expense-template')
router.register(r'profit-check-rule', ProfitCheckRuleViewSet, basename='profit-check-rule')

urlpatterns = router.urls
